### ISSUE TITLE
Multiple Imports mess up the output

### ISSUE THREAD

**Issue by 0Volcanon** [nklbdev/godot-4-importality#18]
**What's the Issue**
Importing multiple files at once messes up the rest.
So, I don't know if this is a problem with the plugin or Godot itself, I've no experience of plugins. When I import multiple files, Godot messes up the results, File A shows up as File B until reimported separately. The most I can figure out is the temp data gets removed during the import process while the next file is being processed. There is an error for unreadable files (see screenshot). In the project, if you select all of the files and hit import, it'll mess up the result.
**![image](https://github.com/nklbdev/godot-4-importality/assets/105208198/a7c6fc86-b20b-4688-822f-3dcf042f2cb9)**
**Minimal Reproduction Project**
[Aseprite Multi Import Issue.zip](https://github.com/nklbdev/godot-4-importality/files/12853568/Aseprite.Multi.Import.Issue.zip)

**Comment by nklbdev** [comment]
Thank you! This is a very valuable note!
I will place temporary files in a separate folder with a unique name each time I import. This will help avoid collisions. Expect a new version today or tomorrow.

**Comment by nklbdev** [comment]
I'm really sorry, but I couldn't devote time to this project this week because I'm very busy at work. I'll try the next one.

**Comment by 0Volcanon** [comment]
No problem. The addon is already a great contribution. It saved my studio a lot of time in development and vastly improved our workflow. Take your time. If I can, I would also help with the project in the future. Thank you for making this plugin, it's been a great help.

**Comment by nklbdev** [comment]
I made each import happen in a separate directory with a unique name. Please take the latest version of the plugin code from the main branch and check if your problem is gone.

**Comment by 0Volcanon** [comment]
Tested with 300+ files and can confirm it works perfectly. Thank you.
