### ISSUE TITLE
Use `EditorSettings` instead of `ProjectSettings`.

### ISSUE THREAD

**Issue by rylydou** [nklbdev/godot-4-importality#19]
Most of settings for this addon seam to be only for the paths to executables. Using Editor Settings instead of Project Settings would work better for teams who use different operating systems.

I think it should be as simple as replacing every instance of `ProjectSettings` with `EditorSettings` in [project_setting.gd](https://github.com/nklbdev/godot-4-importality/blob/main/addons/nklbdev.importality/project_setting.gd).

**Comment by rylydou** [comment]
I will try this change in my project and let you know if there are any problems.

**Comment by nklbdev** [comment]
Thanks, that's a good point. I will also try to transfer the Importality settings to the editor settings.

I'm really sorry, but I couldn't devote time to this project this week because I'm very busy at work. I'll try the next one.

**Comment by nklbdev** [comment]
I tried moving the plugin settings from `ProjectSettings` to `EditorSettings`. I think I succeeded, although there were some minor pitfalls.

Please test the latest version of the [`use_editor_settings_instead_of_project_settings`](https://github.com/nklbdev/godot-4-importality/tree/use_editor_settings_instead_of_project_settings) branch on your project.
