### ISSUE TITLE
Lots of errors, can't seem to figure out how to add the imported Aseprite file to the Godot scene

### ISSUE THREAD

**Issue by golddotasksquestions** [nklbdev/godot-4-importality#2]
On Godot 4.1.1 stable, Windows:

After I installed and enabled the plugin I saved a basic Aseprite Animation (created as a new file, all defaults, just added 4 frames) into the res folder. I then selected the *.aseprite file and in the Import tab I switched to the "Aseprite -> Sprite with AnimationPlayer" preset. I let Godot save and restart and after the restart I tried to drag the *.aseprite file onto the Scene Panel top node of a new scene. This did not work. Then I noticed this wall of red errors:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/11a07454-498e-49a8-b9d1-264d4339d304)

I just closed Godot, restarted and tried again in a new scene, and I noticed there are no errors in the beginning, also none when clicking the *aseprite file, but this block appears as soon as I try to click-drag the aseprite file:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/0397effd-a3f7-4b6c-9931-5bbb1f840c71)

Aseprite File I used:
[Sprite-0002.zip](https://github.com/nklbdev/godot-4-importality/files/12240514/Sprite-0002.zip)

**Comment by nklbdev** [comment]
I couldn't get the same errors as you in the output window, but your file helped me find one bug - a small typo in handling the default animation when no tags were specified in the `*.aseprite`-file.

Please check your new version of the plugin. Perhaps the problem was in this typo. And let me know if anything has changed! 🙏

**Comment by golddotasksquestions** [comment]
I deleted the `Sprite-0002.aseprite` file, uninstalled the addon (first disabled it, then deleted the `nklbdev.importality` folder from the addon folder), then I restarted Godot.

Then I added the `nklbdev.importality` folder from the newly downloaded zip to the addon folder and the the `Sprite-0002.aseprite` file to the res:// folder of my project and started Godot 4.1.1 stable again.

I go to the Plugins in Project Settings and as soon as I enable Importailty, these errors appear:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/63a41855-3300-436e-b865-b2630eb04650)

I then select the `Sprite-0002.aseprite` file and go to the Import tab, select the "Aseprite -> Sprite AnimationPlayer" preset and hit "Reimport", then these errors appear:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/2ef0871e-4871-4b00-8b29-568f6c7fddb0)

If I try to drag the `Sprite-0002.aseprite` file onto the Root node the same errors appear again.

**Comment by nklbdev** [comment]
Try to remove the file `.godot/imported/Sprite-0002.aseprite-aa78087caaed2c076fd048998bb5544ad.ctex`.
And all the files from `.godot/imported/` that names is starting with `Sprite-0002.aseprite`.
And `Sprite-0002.aseprite.import` from project.

They can store old broken data. Let Godot reimport them.

**Comment by golddotasksquestions** [comment]
I closed Godot and deleted all Sprite-0002... files from the project, so from the Import folder as well as from the res:// folder, including the Sprite-0002.aseprite.import file from the res:// folder.

Then I restarted Godot 4.1.1 to verify it would start without complaints. This went fine.

I then closed Godot again and added the Sprite-0002.aseprite file into the res:// folder and then started Godot, which greeted me with this error message:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/92398837-26f4-4d6b-b761-2f22d691cbe6)

**Comment by golddotasksquestions** [comment]
Ok, I went through the [same steps as before](https://github.com/nklbdev/godot-4-importality/issues/2#issuecomment-1662390836), enabeling the addon worked without errors, however after I dragged the aseprite file into the res:// folder, I got these error messages:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/8baefbe8-b370-4f22-9bd1-a9c53e859f12)

**Comment by nklbdev** [comment]
Please, set up temporary files directory path and aseprite command like on screenshot
![settings](https://github.com/nklbdev/godot-4-importality/wiki)

**Comment by golddotasksquestions** [comment]
Is this something you expect all users to do? If so I think it would be necessary to mention this explicitly in the "How to use" section on [Github repo here](https://github.com/nklbdev/godot-4-importality).

Currently the steps just mention the Import Tab and it's settings.

**Comment by nklbdev** [comment]
I'm sorry that this caused you inconvenience. I didn't know it would work. I have described how to work with each editor on the wiki, and I expected users to immediately search for [an article](https://github.com/nklbdev/godot-4-importality/wiki/exporting-data-from-aseprite-(en)) about the editor they are using.

This is helpful for me, thanks. I will fix the readme so as not to mislead users! 👍

**Comment by golddotasksquestions** [comment]
Definitely mention it in the How to that users have to go into the Project settings, otherwise I guarantee you a lot of people will miss this.

I also don't quite understand what folder this Temporary Files Directory Path is. I don't have such a folder or folder structure. Can this be any folder anywhere? If it can be any folder, why not use the OS [user](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-data-dir) or [temp](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-system-dir) folder?

I also find this screenshot confusing as it has settting for apps I might not have. Why does the plugin need a reference to the Aseprite executeable anyway?

**Comment by nklbdev** [comment]
If you don't have the Aseprite application installed, then the plugin will not be able to import data from `*.aseprite`-files, because it does not have the ability to parse these files on its own and flatten all the cels into resulting frames images. I'm sorry, but it is.

You can use any directory on your system as the directory for temporary files. But I advise you to use a directory that will not contain files that other applications work with, so that there are no collisions between them.

**Comment by golddotasksquestions** [comment]
> f you don't have the Aseprite application installed, then the plugin will not be able to import data from *.aseprite-files, because it does not have the ability to parse these files on its own and flatten all the cels into resulting frames images. I'm sorry, but it is.

I would also mention this on the Github repro. A lot of Godot users download premade assets from itch.io, opengameart.com, Kenney and other places which sometimes come as *aseprite files. Knowing this before downloading installing and trying your plugin might save them a lot of time and trial and error.

**Comment by nklbdev** [comment]
Thank you!

I still have an application to test the functionality of the plugin with LibreSprite instead of Aseprite. This is a free analogue of Aseprite. Perhaps if users don't have the option to buy or build Aыeprite from source files, they can use LibreSprite instead.

**Comment by golddotasksquestions** [comment]
So I set the Temp folder and Aseprite executeable path, now I get these errors:

![image](https://github.com/nklbdev/godot-4-importality/assets/47016402/73356294-04ee-43b7-8788-65d29507a459)

I have to say this is a pretty tiring setup experience. My enthusiasm is pretty much gone at this point.

**Comment by nklbdev** [comment]
I understand and again I apologize. Now I will test the plugin on your version of Aceprite. Perhaps it does not support some export option specified in the documentation for its [CLI](https://www.aseprite.org/docs/cli/)

**Comment by nklbdev** [comment]
I added LibreSprite support and simplified usage of Aseprite/LibreSprite CLI.
I hope that now your import will pass without errors.
