### ISSUE TITLE
Can't setup plugin in Godot 4.2 beta 5.

### ISSUE THREAD

**Issue by oleyb** [nklbdev/godot-4-importality#21]
Upon installing via the AssetLib and enabling the plugin, there are no Importality settings under the advanced genera project settings when using Godot 4.2 beta 5.

**Comment by oleyb** [comment]
User error, issue closed.

**Comment by nklbdev** [comment]
I apologize, I have not yet updated all the reference materials with information about changing the location of the settings 😢. They have moved from ProjectSettings to EditorSettings.

**Comment by oleyb** [comment]
No worries, I thought I had just read it wrong. I figured it out eventually, though it almost had my abandon the add-on for something else.
