### ISSUE TITLE
Settings completely missing from the menu

### ISSUE THREAD

**Issue by polypoyo** [nklbdev/godot-4-importality#23]
**Version**: Godot_v4.1.3-stable_linux

**To reproduce**: 
1. Add plugin a project using AssetLib. Enable.
2. Restart editor
3. Search for Importality in the project settings, toplevel general
4. Notice that it's not there

I'm getting the error `The project settging "importality/aseprite_or_libre_sprite_command" is not specified!Specify it in Projest Settings -> General -> Importality.` in the output console so the editor is definitely loading the plugin. Manually specifying the setting does not seem to work either.

**Comment by polypoyo** [comment]
Solved. Turns out it was in the editor settings. Message should be updated but that's a separate issue.

**Comment by nklbdev** [comment]
Thanks for reminding me!
I have posted this information on the main page of the repository.
I need to update the documentation on the wiki, but I just can't seem to find the time to do it. Very busy with main work(((

**Comment by andyfangaf** [comment]
The message is still misleading, it's not been fixed in the PR
