### ISSUE TITLE
Settings not showing in Godot v4.2.1

### ISSUE THREAD

**Issue by baudren** [nklbdev/godot-4-importality#26]
Hi,

thank you for your plugin, it works beautifully!

I have an issue, I started working on my game with the steam version. I installed the plugin there, and it worked as expected.

Now I switched to a fixed release, for more control, and am using the 4.2.1, published on Archlinux. I also checked that the problem is present when download the 4.2.1 directly from the website and opening my project.

When I try to input the path to my aseprite installation, I can not - the settings do not show

![image](https://github.com/nklbdev/godot-4-importality/assets/3526120/7576bb93-a78c-476f-841c-43beb31f248d)

The plugin is installed, and activated:

![image](https://github.com/nklbdev/godot-4-importality/assets/3526120/2d127a6f-5e76-4464-8008-33933ae96a55)

Am I doing something stupid, here? Shouldn't the Importality setting appear under the General Project Settings? At least following the documentation it looks like it:
https://github.com/nklbdev/godot-4-importality/wiki

Thank you in advance,

Cheers

Benjamin

**Comment by nklbdev** [comment]
Good day, Benjamin!
Sorry I can't work on this plugin. I'm very very very busy at work. (((((((

I did not transfer to the wiki the information that the plugin settings moved from the project settings to the editor settings.
All I could do was write a warning on the main page of the plugin in GitHub.

Open the editor settings and there you will find the Importality section.
This will help you avoid storing local path and command settings in the project repository.

**Comment by baudren** [comment]
Thanks, I found it now. Cheers!
